[package]
name = "passmgr-core"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.30", features = ["bundled"] } # SQLite with static linking
chrono = "0.4"               # For timestamps
uuid = { version = "1", features = ["v4"] }  # Unique IDs
